# Generated by Django 3.2.25 on 2026-09-09 01:03
from django.db import migrations

import kolibri.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ("lessons", "0004_nullable_created_by_assigned_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="lesson",
            name="due_date",
            field=kolibri.core.fields.DateTimeTzField(
                blank=True, default=None, null=True
            ),
        ),
        migrations.AddField(
            model_name="lesson",
            name="start_date",
            field=kolibri.core.fields.DateTimeTzField(
                blank=True, default=None, null=True
            ),
        ),
    ]
