# Generated by Django 3.2.25 on 2026-09-09 03:35
import django.db.models.deletion
import morango.models.fields.uuids
from django.db import migrations
from django.db import models

import kolibri.core.fields
import kolibri.utils.time_utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("kolibriauth", "0035_facilitydataset_picture_password_settings"),
    ]

    operations = [
        migrations.CreateModel(
            name="LearnerNodeAssignment",
            fields=[
                (
                    "id",
                    morango.models.fields.uuids.UUIDField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "_morango_dirty_bit",
                    models.BooleanField(default=True, editable=False),
                ),
                ("_morango_source_id", models.CharField(editable=False, max_length=96)),
                (
                    "_morango_partition",
                    models.CharField(editable=False, max_length=128),
                ),
                ("contentnode_id", morango.models.fields.uuids.UUIDField()),
                ("title", models.CharField(max_length=200)),
                (
                    "date_assigned",
                    kolibri.core.fields.DateTimeTzField(
                        default=kolibri.utils.time_utils.local_now, editable=False
                    ),
                ),
                (
                    "assigned_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="node_assignments_created",
                        to="kolibriauth.FacilityUser",
                    ),
                ),
                (
                    "dataset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="kolibriauth.facilitydataset",
                    ),
                ),
                (
                    "learner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="node_assignments",
                        to="kolibriauth.FacilityUser",
                    ),
                ),
            ],
            options={
                "unique_together": {("contentnode_id", "learner")},
            },
        ),
    ]
